### ISSUE TITLE
New challenge proposal for germany

### ISSUE THREAD

**Issue by CodeWithMa** [Tobertet/ToberQuizz#11]
# Checklist

- [x] The challenge complies with the challenge rules.
- [x] Answered the questionnaire.
- [x] Included 256x256 minimal size images in PNG format inside a ZIP with the question number as filename.
- [x] Included challenge data and hashed solutions using Argon2 with the required parameters.

# Questionnaire

- For what country is the challenge? Germany
- What is its topic/theme? German singing Bands / Artists
- How many people that start the challenge do you think will be able to complete it? In %. Maybe 65%? There are ~5 hard questions and the rest should be solvable by everyone.

# Challenge Resources

## Images

[images.zip](https://github.com/Tobertet/ToberQuizz/files/9634201/images.zip)

## Data

[challenge.json.zip](https://github.com/Tobertet/ToberQuizz/files/9634196/challenge.json.zip)

**Comment by Tobertet** [comment]
Thanks a lot for your contribution @CodeWithMa!

The challenge has been added and will be available in the next version of the app (usually takes a few days). I set the starting date to October 1st.

Let's see how many people solve it :)
